# Generated by Django 4.2 on 2024-09-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='2000-01-01', verbose_name='birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='admin', max_length=30, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='admin', max_length=20, verbose_name='nickname'),
            preserve_default=False,
        ),
    ]
