# Generated by Django 4.2 on 2024-09-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="product_tags",
                to="products.hashtag",
                verbose_name="해시태그 목록",
            ),
        ),
    ]
